### ISSUE TITLE
Having troubles with model infer

### ISSUE THREAD

**Issue by Kedao98** [xk-huang/OrdinalCLIP#2]
Hi there, thanks for your great work. Im trying to estimate ages with your model. But I can not find an infer function to predict. Could you tell me how to fetch an infer result on your codes? Thx a lot.

**Comment by xk-huang** [comment]
Hi @Kedao98 , thanks for pointing out! 
I returned to the code and found the entangled implementation of result prediction and metric evaluation. 
Here is the proposed snippet that may help: https://github.com/xk-huang/OrdinalCLIP/compare/main...pred_api
Call `make_predictions` to get the predictions.

Ps: the code snippet hasn't been tested due to limited time, I will catch up later!
